import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    slug: "attack-defense-lab",
    title: "Attack & Defense Security Lab",

    technologies: [
      "Wazuh",
      "ELK Stack",
      "Splunk",
      "Linux",
    ],

    description:
      "Designed a simulated attack-defense environment for collecting, monitoring, and analyzing security logs across multiple systems.",

    overview:
      "A hands-on cybersecurity lab focused on security monitoring, centralized logging, and detection workflows. The environment simulates activity across multiple systems and provides a foundation for investigating suspicious events through SIEM platforms.",

    objectives: [
      "Build a practical security monitoring environment.",
      "Centralize logs from multiple systems.",
      "Practice identifying suspicious activity through security telemetry.",
      "Understand the workflow from attack activity to detection and investigation.",
    ],

    features: [
      "Centralized security log collection.",
      "Wazuh-based endpoint monitoring.",
      "ELK Stack log analysis and visualization.",
      "Splunk-based SIEM investigation.",
      "Linux-based security lab environment.",
    ],

    github: "https://github.com/kaelorphung",
  },

  {
    slug: "credential-dumping-detection",
    title: "Credential Dumping Detection Lab",

    technologies: [
      "Windows",
      "Sysmon",
      "Mimikatz",
      "Detection Engineering",
    ],

    description:
      "Built a Windows security lab to study credential dumping techniques and develop log-based detections using Sysmon and SIEM platforms.",

    overview:
      "A Windows-based detection engineering lab focused on understanding credential dumping behavior and the telemetry generated by suspicious processes. The project explores how endpoint logs can be collected, analyzed, and converted into useful detection logic.",

    objectives: [
      "Understand the telemetry generated by credential dumping activity.",
      "Configure Sysmon for detailed Windows event collection.",
      "Analyze suspicious process and authentication-related events.",
      "Develop detection logic based on observable behaviors.",
    ],

    features: [
      "Windows security lab environment.",
      "Sysmon event collection and monitoring.",
      "Analysis of suspicious process activity.",
      "Credential dumping behavior research.",
      "Log-based detection engineering.",
      "SIEM-oriented investigation workflow.",
    ],

    github: "https://github.com/kaelorphung",
  },

  {
    slug: "ecommerce",
    title: "Basic E-commerce Website",

    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
    ],

    description:
      "Developed a responsive shopping website as a web development practice project.",

    overview:
      "A frontend-focused e-commerce practice project built to strengthen fundamental web development skills. The project focuses on responsive layouts, product presentation, user interaction, and clean interface structure.",

    objectives: [
      "Practice building responsive web interfaces.",
      "Improve HTML and CSS fundamentals.",
      "Use JavaScript to implement interactive behavior.",
      "Build a structured shopping experience from scratch.",
    ],

    features: [
      "Responsive e-commerce layout.",
      "Product presentation interface.",
      "Interactive JavaScript components.",
      "Structured HTML and CSS styling.",
      "Mobile-friendly design practice.",
    ],

    github: "https://github.com/kaelorphung",
  },
];